import { Router, Request, Response } from 'express';
import path from 'path';
import multer from 'multer';
import fs from 'fs';
import {
  runGenerate,
  buildDataset,
  computeFingerprint,
  loadRawDataset,
  loadFingerprint,
  saveRawDataset,
  refilterDashboard,
  mergeDatasets,
  integrationsSummary,
  loadIntegrations,
  testAnthropicConnection,
  testLlmConnection,
  jiraConfigFromConnection,
  qmetryConfigFromConnection,
  fetchJiraIssues,
  fetchProjectCycles,
  fetchProjectFolders,
  fetchFolderCycleHealth,
  searchQmetryTestCycles,
  emptyConnections,
  canonicalProjectKey,
  canonicalProjectOrUndefined,
  dataDateBounds,
  workspaceIdFromName,
  filterConnectionsForWorkspace,
  stampDatasetWorkspace,
} from 'qa-dashboard-batch';
import type { ApiFetchScope, Dataset, LlmSelectionInput, UserConnections, JiraConnectionInput, QmetryConnectionInput, FilterParams, ReportType } from 'qa-dashboard-batch';
import { getEnvStatus } from '../loadRepoEnv';
import { generateReportPdf, type ReportBrandingPayload } from '../services/reportPdf';

const router = Router();
const ROOT = process.env.PROJECT_ROOT || path.resolve(__dirname, '../../../..');
const DATA_ROOT = process.env.DATA_ROOT || (process.env.INPUT_DIR ? path.dirname(process.env.INPUT_DIR) : path.join(ROOT, 'data'));
const LEGACY_INPUT_DIR = process.env.INPUT_DIR || path.join(DATA_ROOT, 'input');
const LEGACY_OUTPUT_DIR = process.env.OUTPUT_DIR || path.join(DATA_ROOT, 'output');
const PROJECT_DATA_DIR = process.env.PROJECT_DATA_DIR || path.join(DATA_ROOT, 'projects');
const CONFIG_DIR = process.env.CONFIG_DIR || path.join(ROOT, 'config');

fs.mkdirSync(LEGACY_INPUT_DIR, { recursive: true });
fs.mkdirSync(LEGACY_OUTPUT_DIR, { recursive: true });
fs.mkdirSync(PROJECT_DATA_DIR, { recursive: true });
fs.mkdirSync(CONFIG_DIR, { recursive: true });

const GENERATED_OUTPUT_FILES = ['raw-dataset.json', 'dataset-fingerprint.txt', 'dashboard-data.json', 'report.md', 'report-meta.json'];
const REPORT_OUTPUT_FILES = ['report.md', 'report-meta.json'];
const IMPORT_CACHE_FILE = 'raw-dataset.imported.json';
const LIVE_CACHE_FILE = 'raw-dataset.live.json';
const PROJECT_META_FILE = 'project.json';
const REPORT_TYPES: ReportType[] = ['full', 'executive', 'testers', 'defects', 'cycles'];

type BuildMode = 'cached' | 'import-only' | 'live';
type DashboardPayload = ReturnType<typeof refilterDashboard>;
interface DataDirs { inputDir: string; outputDir: string; project?: string; slug?: string }

function requestId(req: Request): string { return (req as Request & { requestId?: string }).requestId || req.header('x-request-id') || 'no-request-id'; }
function log(req: Request, message: string, data?: Record<string, unknown>): void { console.log(`[api] [${requestId(req)}] ${message}`, data || ''); }
function logError(req: Request, message: string, err: unknown, data?: Record<string, unknown>): void { console.error(`[api] [${requestId(req)}] ${message}`, { ...data, error: err instanceof Error ? err.message : String(err) }); }
function validDate(value?: string): string | undefined { const v = (value || '').trim(); return /^\d{4}-\d{2}-\d{2}$/.test(v) ? v : undefined; }
function queryString(value: unknown, fallback = ''): string { if (typeof value === 'string') return value; if (Array.isArray(value) && typeof value[0] === 'string') return value[0]; return fallback; }
function cleanProject(value?: string): string | undefined { const id = workspaceIdFromName(value) || (value || '').trim(); return id && id !== 'all' ? id : undefined; }
function requestProject(req: Request): string | undefined { const body = req.body as Partial<FilterParams> | undefined; return cleanProject(queryString(req.query.project) || body?.project); }
function legacyDirs(): DataDirs { return { inputDir: LEGACY_INPUT_DIR, outputDir: LEGACY_OUTPUT_DIR }; }
function projectDirs(project?: string | null): DataDirs { const clean = cleanProject(project || undefined); if (!clean) return legacyDirs(); const root = path.join(PROJECT_DATA_DIR, clean); return { inputDir: path.join(root, 'input'), outputDir: path.join(root, 'output'), project: clean, slug: clean }; }
function ensureDataDirs(dirs: DataDirs): void { fs.mkdirSync(dirs.inputDir, { recursive: true }); fs.mkdirSync(dirs.outputDir, { recursive: true }); if (dirs.project && dirs.slug) fs.writeFileSync(path.join(path.dirname(dirs.inputDir), PROJECT_META_FILE), JSON.stringify({ project: dirs.project, slug: dirs.slug, updatedAt: new Date().toISOString() }, null, 2)); }
function outputPath(dirs: DataDirs, fileName: string): string { return path.join(dirs.outputDir, fileName); }
function removeOutputFile(dirs: DataDirs, fileName: string): string | null { const filePath = outputPath(dirs, fileName); if (!fs.existsSync(filePath)) return null; fs.unlinkSync(filePath); return fileName; }
function clearOutputFiles(dirs: DataDirs, fileNames: string[] = GENERATED_OUTPUT_FILES): string[] { const removed = new Set<string>(); for (const fileName of fileNames) { const deleted = removeOutputFile(dirs, fileName); if (deleted) removed.add(deleted); } return [...removed]; }
function rowCounts(dataset: Dataset): { executions: number; issues: number; uat: number } { return { executions: dataset.executions.length, issues: dataset.issues.length, uat: dataset.uat.length }; }
function totalRows(dataset: Dataset): number { const counts = rowCounts(dataset); return counts.executions + counts.issues + counts.uat; }
function cleanApiScope(scope?: ApiFetchScope): ApiFetchScope | undefined { if (!scope) return undefined; const next: ApiFetchScope = {}; const startDate = validDate(scope.startDate); const endDate = validDate(scope.endDate); if (startDate) next.startDate = startDate; if (endDate) next.endDate = endDate; return next.startDate || next.endDate ? next : undefined; }
function apiScopeFromFilter(filter: Partial<FilterParams>): ApiFetchScope | undefined { return cleanApiScope({ startDate: filter.startDate, endDate: filter.endDate }); }
function filterFromBody(body: Partial<FilterParams>): FilterParams { return { startDate: body.startDate, endDate: body.endDate, search: body.search, result: body.result || 'all', project: cleanProject(body.project) }; }
function buildOptions(mode: BuildMode, apiScope?: ApiFetchScope) { return { apiScope: mode === 'live' ? cleanApiScope(apiScope) : undefined, liveSync: mode === 'live', includeFiles: mode !== 'live' }; }
function projectRows(dataset: Dataset): Array<{ project: string; rows: number }> { const counts = new Map<string, number>(); const add = (project?: string, rows = 1) => { const key = project || 'UNKNOWN'; counts.set(key, (counts.get(key) || 0) + rows); }; for (const row of dataset.executions) add(row.project); for (const row of dataset.issues) add(row.project); for (const row of dataset.uat) add(row.project); return [...counts.entries()].map(([project, rows]) => ({ project, rows })).sort((a, b) => a.project.localeCompare(b.project)); }
function datasetProjectsSummary(dataset: Dataset): string { const rows = projectRows(dataset); if (!rows.length) return 'no projects / 0 rows'; return rows.map((p) => `${p.project} (${p.rows} rows)`).join(', '); }
function noMetricsMessage(project: string | undefined, startDate: string | undefined, endDate: string | undefined, dataset: Dataset): string { const requestedProject = project && project !== 'all' ? project : 'all projects'; const start = startDate || 'any'; const end = endDate || 'any'; return `No metrics for ${requestedProject} in ${start}..${end}. Dataset contains: ${datasetProjectsSummary(dataset)}. Re-sync imported data if a project is missing.`; }
function hasMetrics(payload: DashboardPayload): boolean { return Boolean(payload.overview.totalCases || payload.storyBug.story || payload.storyBug.bug || payload.defectBacklog.openTotal || payload.cycles.length || payload.testers.length || payload.uat?.total); }
function cacheFileForMode(mode: BuildMode): string | null { if (mode === 'import-only') return IMPORT_CACHE_FILE; if (mode === 'live') return LIVE_CACHE_FILE; return null; }
function loadDatasetFile(dirs: DataDirs, fileName: string): Dataset | null { const filePath = outputPath(dirs, fileName); if (!fs.existsSync(filePath)) return null; return JSON.parse(fs.readFileSync(filePath, 'utf8')) as Dataset; }
function saveDatasetFile(dirs: DataDirs, fileName: string, dataset: Dataset): void { fs.mkdirSync(dirs.outputDir, { recursive: true }); fs.writeFileSync(outputPath(dirs, fileName), JSON.stringify(dataset, null, 2)); }
function projectMatchesScope(project: string | undefined, scope?: ApiFetchScope): boolean { const selected = canonicalProjectOrUndefined(scope?.project); if (!selected) return true; return canonicalProjectKey(project || '') === selected; }
function dateMatchesScope(dates: Array<string | null | undefined>, scope?: ApiFetchScope): boolean { const startDate = validDate(scope?.startDate); const endDate = validDate(scope?.endDate); if (!startDate && !endDate) return true; return dates.some((raw) => { const date = validDate(raw || undefined); return Boolean(date && (!startDate || date >= startDate) && (!endDate || date <= endDate)); }); }
function issueMatchesScope(row: Dataset['issues'][number], scope?: ApiFetchScope): boolean { return projectMatchesScope(row.project, scope) && dateMatchesScope([row.createdAt, row.updatedAt, row.resolvedAt], scope); }
function executionMatchesScope(row: Dataset['executions'][number], scope?: ApiFetchScope): boolean { return projectMatchesScope(row.project, scope) && dateMatchesScope([row.executedAt, row.updatedAt], scope); }
function liveDatasetSlice(dataset: Dataset, executions: Dataset['executions'], issues: Dataset['issues'], files: Dataset['files']): Dataset { return { executions, issues, uat: [], projects: [...new Set([...executions.map((e) => e.project), ...issues.map((i) => i.project)].filter(Boolean))].sort(), files, meta: { parsedAt: new Date().toISOString(), fetchedAt: dataset.meta.fetchedAt, sourceFiles: [], warnings: [], integrations: { jira: issues.length > 0, qmetry: executions.length > 0 }, deduped: { executions: 0, issues: 0, uat: 0 } } }; }
function preserveLiveCache(dirs: DataDirs, freshDataset: Dataset, apiScope?: ApiFetchScope): Dataset { const previous = loadDatasetFile(dirs, LIVE_CACHE_FILE); if (!previous) return freshDataset; const freshJira = freshDataset.issues.some((row) => row.source === 'jira-api') || freshDataset.files.some((file) => file.source === 'jira-api'); const freshQmetry = freshDataset.executions.some((row) => row.source === 'qmetry') || freshDataset.files.some((file) => file.source === 'qmetry-api'); const previousJira = previous.issues.filter((row) => row.source === 'jira-api'); const previousQmetry = previous.executions.filter((row) => row.source === 'qmetry'); const warnings = [...freshDataset.meta.warnings]; const preservedIssues = freshJira ? previousJira.filter((row) => !issueMatchesScope(row, apiScope)) : previousJira; const preservedExecutions = freshQmetry ? previousQmetry.filter((row) => !executionMatchesScope(row, apiScope)) : previousQmetry; const preservedFiles = previous.files.filter((file) => { if (file.source === 'jira-api') return !freshJira; if (file.source === 'qmetry-api') return !freshQmetry; return false; }); if (!freshJira && previousJira.length && freshDataset.meta.integrations.jira) warnings.push('JIRA live search returned no fresh issue rows for the selected scope; kept previous cached JIRA rows.'); if (!freshQmetry && previousQmetry.length && freshDataset.meta.integrations.qmetry) warnings.push('QMetry live search returned no fresh execution rows for the selected scope; kept previous cached QMetry rows.'); const preserved = liveDatasetSlice(previous, preservedExecutions, preservedIssues, preservedFiles); const freshWithWarnings: Dataset = { ...freshDataset, meta: { ...freshDataset.meta, warnings } }; return mergeDatasets([preserved, freshWithWarnings]); }
function hasLiveSources(connections: UserConnections): boolean { if (connections.jira.some((c) => c.enabled !== false && c.syncIssues !== false)) return true; if (connections.qmetry.some((c) => c.enabled !== false && c.syncExecutions !== false)) return true; const summary = integrationsSummary(CONFIG_DIR); return Boolean(summary.jira.enabled || summary.qmetry.enabled); }
function mergedSourceDataset(dirs: DataDirs, updatedMode?: BuildMode, updatedDataset?: Dataset): Dataset { const parts: Dataset[] = []; const importDataset = updatedMode === 'import-only' ? updatedDataset : loadDatasetFile(dirs, IMPORT_CACHE_FILE); const liveDataset = updatedMode === 'live' ? updatedDataset : loadDatasetFile(dirs, LIVE_CACHE_FILE); if (importDataset) parts.push(importDataset); if (liveDataset) parts.push(liveDataset); return mergeDatasets(parts); }
function projectMetaProject(projectRoot: string): string | null { const metaPath = path.join(projectRoot, PROJECT_META_FILE); try { if (!fs.existsSync(metaPath)) return null; const meta = JSON.parse(fs.readFileSync(metaPath, 'utf8')) as { project?: string }; return cleanProject(meta.project); } catch { return null; } }
function allProjectDirs(): DataDirs[] { if (!fs.existsSync(PROJECT_DATA_DIR)) return []; return fs.readdirSync(PROJECT_DATA_DIR, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => { const root = path.join(PROJECT_DATA_DIR, d.name); const project = projectMetaProject(root) || d.name; return { inputDir: path.join(root, 'input'), outputDir: path.join(root, 'output'), project, slug: d.name }; }); }
function loadAllProjectsDataset(): Dataset | null { const datasets: Dataset[] = []; for (const dirs of allProjectDirs()) { const dataset = loadRawDataset(dirs.outputDir); if (dataset && totalRows(dataset) > 0) datasets.push(dataset); } const legacy = loadRawDataset(LEGACY_OUTPUT_DIR); if (legacy && totalRows(legacy) > 0) datasets.push(legacy); return datasets.length ? mergeDatasets(datasets) : null; }

async function refreshGeneratedOutputs(req: Request, dirs: DataDirs, connections: UserConnections, apiScope?: ApiFetchScope, dashboardFilter: Partial<FilterParams> = {}, mode: BuildMode = 'live') { ensureDataDirs(dirs); const workspaceConnections = filterConnectionsForWorkspace(connections, dirs.project); const options = buildOptions(mode, apiScope); const sourceConnections = mode === 'live' ? workspaceConnections : emptyConnections(); const fingerprint = computeFingerprint(dirs.inputDir, CONFIG_DIR, sourceConnections, options); const freshBuiltDataset = await buildDataset(dirs.inputDir, CONFIG_DIR, sourceConnections, options); const scopedBuiltDataset = stampDatasetWorkspace(freshBuiltDataset, dirs.project); const sourceDataset = mode === 'live' ? preserveLiveCache(dirs, scopedBuiltDataset, options.apiScope) : scopedBuiltDataset; const sourceCacheFile = cacheFileForMode(mode); if (sourceCacheFile) saveDatasetFile(dirs, sourceCacheFile, sourceDataset); const dataset = mergedSourceDataset(dirs, mode, sourceDataset); const counts = rowCounts(dataset); const removed = clearOutputFiles(dirs, REPORT_OUTPUT_FILES); if (totalRows(dataset) === 0) { removed.push(...clearOutputFiles(dirs, ['raw-dataset.json', 'dataset-fingerprint.txt', 'dashboard-data.json'])); log(req, 'generated outputs cleared; no source data remains', { mode, rowCounts: counts, removed, apiScope: options.apiScope, dirs }); return { rebuilt: false, rowCounts: counts, removed, warnings: dataset.meta.warnings, files: dataset.files, projects: dataset.projects }; } saveRawDataset(dirs.outputDir, dataset, fingerprint); const payload = refilterDashboard(dataset, { ...dashboardFilter, project: dirs.project }); fs.writeFileSync(outputPath(dirs, 'dashboard-data.json'), JSON.stringify(payload, null, 2)); log(req, 'generated outputs refreshed', { mode, rowCounts: counts, warnings: dataset.meta.warnings, projects: dataset.projects, apiScope: options.apiScope, dirs }); return { rebuilt: true, rowCounts: counts, removed, warnings: dataset.meta.warnings, files: dataset.files, projects: dataset.projects, dashboard: payload }; }
function connectionSummary(connections: UserConnections) { return { jira: connections.jira.map((c) => ({ workspaceName: c.workspaceName || c.name, name: c.name, baseUrl: c.baseUrl, projectKeys: c.projectKeys?.join(',') || '' })), qmetry: connections.qmetry.map((c) => ({ workspaceName: c.workspaceName || c.name, name: c.name, baseUrl: c.baseUrl, projectKey: c.projectKey, projectId: c.projectId || '', folderId: c.folderId || '' })) }; }
function resolveConnections(req: Request): UserConnections { const raw = req.header('x-user-connections'); if (!raw) return emptyConnections(); try { const parsed = JSON.parse(raw) as Partial<UserConnections>; const connections = { jira: Array.isArray(parsed.jira) ? parsed.jira : [], qmetry: Array.isArray(parsed.qmetry) ? parsed.qmetry : [] }; log(req, 'resolved browser connections', connectionSummary(connections)); return connections; } catch (err) { logError(req, 'failed to parse x-user-connections header', err); return emptyConnections(); } }
function resolveAnthropicKey(req: Request): { key: string; source: 'user' | 'server' | 'none' } { const headerKey = (req.header('x-anthropic-key') || '').trim(); if (headerKey) return { key: headerKey, source: 'user' }; const envKey = (process.env.ANTHROPIC_API_KEY || '').trim(); if (envKey) return { key: envKey, source: 'server' }; return { key: '', source: 'none' }; }
async function ensureDataset(req: Request, dirs: DataDirs, connections: UserConnections, apiScope?: ApiFetchScope, mode: BuildMode = 'import-only'): Promise<{ dataset: Dataset; fingerprint: string } | null> { ensureDataDirs(dirs); const workspaceConnections = filterConnectionsForWorkspace(connections, dirs.project); const options = buildOptions(mode, apiScope); const sourceConnections = mode === 'live' ? workspaceConnections : connections; const fingerprint = computeFingerprint(dirs.inputDir, CONFIG_DIR, sourceConnections, options); const cached = loadFingerprint(dirs.outputDir); let dataset = loadRawDataset(dirs.outputDir); log(req, 'ensureDataset:start', { inputDir: dirs.inputDir, configDir: CONFIG_DIR, outputDir: dirs.outputDir, project: dirs.project, fingerprint, cachedFingerprint: cached, apiScope: options.apiScope, mode }); if (dataset && (cached === fingerprint || mode === 'cached')) return { dataset, fingerprint: cached || fingerprint }; if (mode === 'cached') return null; try { const builtDataset = await buildDataset(dirs.inputDir, CONFIG_DIR, sourceConnections, options); const scopedBuiltDataset = stampDatasetWorkspace(builtDataset, dirs.project); const sourceDataset = mode === 'live' ? preserveLiveCache(dirs, scopedBuiltDataset, options.apiScope) : scopedBuiltDataset; if (totalRows(sourceDataset) === 0) return null; const sourceCacheFile = cacheFileForMode(mode); if (sourceCacheFile) saveDatasetFile(dirs, sourceCacheFile, sourceDataset); const merged = mergedSourceDataset(dirs, mode, sourceDataset); saveRawDataset(dirs.outputDir, merged, fingerprint); return { dataset: merged, fingerprint }; } catch (err) { logError(req, 'ensureDataset:build failed', err, { mode }); return dataset ? { dataset, fingerprint: cached || fingerprint } : null; } }
function parseFilterParams(req: Request): FilterParams { return { startDate: queryString(req.query.startDate) || undefined, endDate: queryString(req.query.endDate) || undefined, search: queryString(req.query.search) || undefined, result: (queryString(req.query.result, 'all') as 'all' | 'PASS' | 'FAIL' | 'BLOCKED') || 'all', project: cleanProject(queryString(req.query.project)) }; }
function selectQmetryConnection(connections: UserConnections, connectionId?: string, workspaceId?: string): QmetryConnectionInput | null { const scoped = filterConnectionsForWorkspace(connections, workspaceId).qmetry; if (!scoped.length) return null; if (connectionId) return scoped.find((c) => c.id === connectionId) || scoped[0]; return scoped[0]; }

router.get('/status', (_req: Request, res: Response) => res.json({ apiKeyConfigured: Boolean(process.env.ANTHROPIC_API_KEY || process.env.OPENAI_API_KEY || process.env.GEMINI_API_KEY || process.env.CUSTOM_LLM_API_KEY), llmProvidersConfigured: { anthropic: Boolean(process.env.ANTHROPIC_API_KEY), openai: Boolean(process.env.OPENAI_API_KEY), gemini: Boolean(process.env.GEMINI_API_KEY), custom: Boolean(process.env.CUSTOM_LLM_API_KEY) }, jiraConfigured: Boolean(process.env.JIRA_EMAIL && process.env.JIRA_API_TOKEN), projectRoot: process.env.PROJECT_ROOT || ROOT, dataRoot: DATA_ROOT, projectDataDir: PROJECT_DATA_DIR }));
router.get('/env', (_req: Request, res: Response) => res.json(getEnvStatus()));
router.post('/llm/test', async (req: Request, res: Response) => { log(req, 'POST /llm/test:start', { provider: (req.body as LlmSelectionInput | undefined)?.provider, model: (req.body as LlmSelectionInput | undefined)?.model }); try { const result = await testLlmConnection((req.body || {}) as LlmSelectionInput, CONFIG_DIR); log(req, 'POST /llm/test:done', { ok: result.ok, provider: result.provider, model: result.model, error: result.error }); res.json(result); } catch (err) { logError(req, 'POST /llm/test:failed', err); res.status(500).json({ ok: false, route: 'direct', error: (err as Error).message || String(err), requestId: requestId(req) }); } });
router.get('/anthropic/test', async (req: Request, res: Response) => { const key = resolveAnthropicKey(req); log(req, 'GET /anthropic/test:start', { keySource: key.source, configDir: CONFIG_DIR }); try { const result = await testAnthropicConnection(key.key, CONFIG_DIR); log(req, 'GET /anthropic/test:done', { ok: result.ok, route: result.route, elapsedMs: result.elapsedMs, error: result.error }); res.json(result); } catch (err) { logError(req, 'GET /anthropic/test:failed', err); res.status(500).json({ ok: false, route: 'direct', error: (err as Error).message || String(err), requestId: requestId(req) }); } });

const storage = multer.diskStorage({ destination: (req, _file, cb) => { const project = requestProject(req); if (!project) return cb(new Error('Select a specific project/workspace before uploading files.')); const dirs = projectDirs(project); ensureDataDirs(dirs); cb(null, dirs.inputDir); }, filename: (_req, file, cb) => cb(null, `${Date.now()}_${path.basename(file.originalname).replace(/[/\\]/g, '_')}`) });
const upload = multer({ storage, limits: { fileSize: 20 * 1024 * 1024 }, fileFilter: (_req, file, cb) => { const ext = path.extname(file.originalname).toLowerCase(); if (ext === '.xlsx' || ext === '.xls') cb(null, true); else cb(new Error('Only .xlsx and .xls files are allowed')); } });

router.post('/generate', async (req: Request, res: Response) => { const { startDate, endDate, reportType, search, result, project, llm } = req.body as { startDate?: string; endDate?: string; reportType?: string; search?: string; result?: string; project?: string; llm?: LlmSelectionInput }; const clean = cleanProject(project); const dirs = projectDirs(clean); const connections = filterConnectionsForWorkspace(resolveConnections(req), clean); const key = resolveAnthropicKey(req); log(req, 'POST /generate:start', { startDate, endDate, reportType, search, result, project: clean, keySource: key.source, connections: connectionSummary(connections), dirs }); const type = REPORT_TYPES.includes(reportType as ReportType) ? (reportType as ReportType) : 'full'; try { const resultPayload = await runGenerate({ startDate, endDate, reportType: type, search, result: (result as 'all') || 'all', project: clean, inputDir: dirs.inputDir, outputDir: dirs.outputDir, configDir: CONFIG_DIR, apiKey: key.key || undefined, llm, connections }); return res.status(200).json({ ...resultPayload, requestId: requestId(req) }); } catch (err) { logError(req, 'POST /generate:failed', err); return res.status(500).json({ ok: false, error: (err as Error).message, requestId: requestId(req) }); } });
router.get('/dashboard', async (req: Request, res: Response) => { const filter = parseFilterParams(req); const connections = resolveConnections(req); if (filter.project) { const dirs = projectDirs(filter.project); const cached = await ensureDataset(req, dirs, connections, undefined, 'cached'); if (cached) return res.json(refilterDashboard(cached.dataset, { ...filter, project: filter.project })); return res.status(404).json({ error: `No dashboard generated yet for ${filter.project}. Import files for this workspace, then sync.`, requestId: requestId(req) }); } const all = loadAllProjectsDataset(); if (all) return res.json(refilterDashboard(all, filter)); const legacy = await ensureDataset(req, legacyDirs(), emptyConnections(), undefined, 'import-only'); if (legacy) return res.json(refilterDashboard(legacy.dataset, filter)); return res.status(404).json({ error: 'No dashboard generated yet. Select a workspace, import files, then sync imported data.', requestId: requestId(req) }); });
router.post('/dashboard/search', async (req: Request, res: Response) => { const connections = resolveConnections(req); const filter = filterFromBody(req.body as Partial<FilterParams>); const apiScope = apiScopeFromFilter(filter); const dirs = projectDirs(filter.project); try { if (filter.project && hasLiveSources(filterConnectionsForWorkspace(connections, filter.project))) { const sync = await refreshGeneratedOutputs(req, dirs, connections, apiScope, filter, 'live'); if (sync.dashboard) return res.json({ ok: true, dashboard: sync.dashboard, rowCounts: sync.rowCounts, warnings: sync.warnings, projects: sync.projects, source: 'live-search', requestId: requestId(req) }); } const cached = filter.project ? await ensureDataset(req, dirs, connections, undefined, 'cached') : null; if (cached) return res.json({ ok: true, dashboard: refilterDashboard(cached.dataset, filter), rowCounts: rowCounts(cached.dataset), warnings: cached.dataset.meta.warnings, projects: cached.dataset.projects, source: 'cached', requestId: requestId(req) }); const all = filter.project ? null : loadAllProjectsDataset(); if (all) return res.json({ ok: true, dashboard: refilterDashboard(all, filter), rowCounts: rowCounts(all), warnings: all.meta.warnings, projects: all.projects, source: 'all-projects', requestId: requestId(req) }); return res.status(404).json({ ok: false, error: 'No cached dashboard data. Select a workspace and sync imported files or JIRA/QMetry first.', requestId: requestId(req) }); } catch (err) { logError(req, 'POST /dashboard/search:failed', err); return res.status(500).json({ ok: false, error: (err as Error).message, requestId: requestId(req) }); } });
router.get('/cycles/folders', async (req: Request, res: Response) => { const project = cleanProject(queryString(req.query.project)); const connections = resolveConnections(req); const conn = selectQmetryConnection(connections, queryString(req.query.connectionId), project); if (conn) { try { const folders = await fetchProjectFolders(qmetryConfigFromConnection(conn)); const cycles = await fetchProjectCycles(qmetryConfigFromConnection(conn)); return res.json({ source: 'qmetry-live', connection: conn.name, connectionId: conn.id, folders, cycles }); } catch (err) { logError(req, `GET /cycles/folders:qmetry failed for ${conn.name}`, err); } } const dirs = projectDirs(project); const cached = await ensureDataset(req, dirs, connections, undefined, 'cached'); if (!cached) return res.json({ source: 'imported', folders: [{ id: 'all', name: 'All imported cycles' }], cycles: [] }); const seen = new Map<string, string>(); for (const e of cached.dataset.executions) if (e.cycleKey && !seen.has(e.cycleKey)) seen.set(e.cycleKey, e.cycleName || e.cycleKey); res.json({ source: 'imported', folders: [{ id: 'all', name: 'All imported cycles' }], cycles: [...seen.entries()].map(([id, name]) => ({ id, name })) }); });
router.get('/cycles/by-folder', async (req: Request, res: Response) => { const connections = resolveConnections(req); const filter = parseFilterParams(req); const folderId = queryString(req.query.folderId, 'all') || 'all'; const conn = selectQmetryConnection(connections, queryString(req.query.connectionId), filter.project); const scope = apiScopeFromFilter(filter); if (conn) { try { const result = await fetchFolderCycleHealth(qmetryConfigFromConnection(conn), folderId === 'all' ? undefined : folderId, scope); return res.json({ source: 'qmetry-live', connection: conn.name, connectionId: conn.id, folderId, cycles: result.cycles.map((c) => ({ ...c, project: filter.project })), warnings: result.error ? [result.error] : [] }); } catch (err) { logError(req, `GET /cycles/by-folder:qmetry failed for ${conn.name}`, err); } } const dirs = projectDirs(filter.project); const cached = await ensureDataset(req, dirs, connections, undefined, 'cached'); if (!cached) return res.json({ source: 'imported', folderId, cycles: [] }); res.json({ source: 'imported', folderId, cycles: refilterDashboard(cached.dataset, filter).cycles }); });
router.get('/report', (req: Request, res: Response) => { const project = cleanProject(queryString(req.query.project)); const dirs = projectDirs(project); const mdPath = path.join(dirs.outputDir, 'report.md'); const metaPath = path.join(dirs.outputDir, 'report-meta.json'); if (!fs.existsSync(mdPath)) return res.status(404).json({ error: 'No report generated yet.' }); res.json({ markdown: fs.readFileSync(mdPath, 'utf8'), meta: fs.existsSync(metaPath) ? JSON.parse(fs.readFileSync(metaPath, 'utf8')) : {} }); });
router.post('/report/pdf', async (req: Request, res: Response) => { const { startDate, endDate, reportType, kpiStyle, project, branding } = req.body as { startDate?: string; endDate?: string; reportType?: string; kpiStyle?: string; project?: string; branding?: ReportBrandingPayload }; const clean = cleanProject(project); const dirs = projectDirs(clean); const connections = resolveConnections(req); const type = REPORT_TYPES.includes(reportType as ReportType) ? (reportType as ReportType) : 'executive'; const kpi = ['editorial', 'framed', 'minimal'].includes(kpiStyle || '') ? kpiStyle! : 'editorial'; const cached = await ensureDataset(req, dirs, connections, undefined, 'cached'); if (!cached) return res.status(404).json({ error: 'No dashboard data. Search or sync data before downloading PDF.', requestId: requestId(req) }); const payload = refilterDashboard(cached.dataset, { startDate, endDate, project: clean }); if (!hasMetrics(payload)) return res.status(404).json({ error: noMetricsMessage(clean, startDate, endDate, cached.dataset), requestId: requestId(req), projects: projectRows(cached.dataset) }); const bounds = (!startDate || !endDate) ? dataDateBounds(cached.dataset) : null; const effectiveStartDate = startDate || bounds?.min || ''; const effectiveEndDate = endDate || bounds?.max || ''; try { const pdfBuffer = await generateReportPdf(effectiveStartDate, effectiveEndDate, type, kpi, clean, branding); const filename = `qa-report${clean ? `-${clean}` : ''}-${effectiveStartDate}-to-${effectiveEndDate}.pdf`; res.setHeader('Content-Type', 'application/pdf'); res.setHeader('Content-Disposition', `attachment; filename="${filename}"`); res.send(pdfBuffer); } catch (err) { logError(req, 'POST /report/pdf:failed', err, { project: clean }); res.status(500).json({ error: `PDF generation failed: ${(err as Error).message}`, requestId: requestId(req) }); } });
router.get('/integrations', (req: Request, res: Response) => { const summary = integrationsSummary(CONFIG_DIR); const cfg = loadIntegrations(CONFIG_DIR); const userConnections = resolveConnections(req); res.json({ ...summary, config: { jira: { enabled: cfg.jira.enabled, projectKeys: cfg.jira.projectKeys, jql: cfg.jira.jql }, qmetry: { enabled: cfg.qmetry.enabled, projectKey: cfg.qmetry.projectKey, projectId: cfg.qmetry.projectId } }, userConnections: { jira: userConnections.jira.map((c) => ({ id: c.id, name: c.name, workspaceName: c.workspaceName, baseUrl: c.baseUrl })), qmetry: userConnections.qmetry.map((c) => ({ id: c.id, name: c.name, workspaceName: c.workspaceName, baseUrl: c.baseUrl })) } }); });
router.post('/integrations/test', async (req: Request, res: Response) => { const connections = resolveConnections(req); try { const dataset = await buildDataset(LEGACY_INPUT_DIR, CONFIG_DIR, connections, { liveSync: true }); res.json({ ok: true, executions: dataset.executions.length, issues: dataset.issues.length, uat: dataset.uat.length, warnings: dataset.meta.warnings }); } catch (err) { logError(req, 'POST /integrations/test:failed', err); res.status(500).json({ ok: false, error: (err as Error).message, requestId: requestId(req) }); } });
router.post('/integrations/sync', async (req: Request, res: Response) => { const connections = resolveConnections(req); const filter = filterFromBody(req.body as Partial<FilterParams>); if (!filter.project) return res.status(400).json({ ok: false, error: 'Select a specific workspace before syncing live JIRA/QMetry data.', requestId: requestId(req) }); const dirs = projectDirs(filter.project); const apiScope = apiScopeFromFilter(filter); try { const sync = await refreshGeneratedOutputs(req, dirs, connections, apiScope, filter, 'live'); return res.json({ ok: true, ...sync, requestId: requestId(req) }); } catch (err) { logError(req, 'POST /integrations/sync:failed', err); return res.status(500).json({ ok: false, error: (err as Error).message, requestId: requestId(req) }); } });
router.post('/integrations/test-connection', async (req: Request, res: Response) => { const { type, connection } = req.body as { type?: 'jira' | 'qmetry'; connection?: JiraConnectionInput | QmetryConnectionInput }; if (!type || !connection) return res.status(400).json({ ok: false, error: 'type and connection are required', requestId: requestId(req) }); try { if (type === 'jira') { const { issues, error } = await fetchJiraIssues({ ...jiraConfigFromConnection(connection as JiraConnectionInput), pageSize: 5 }); if (error) return res.json({ ok: false, error }); return res.json({ ok: true, count: issues.length }); } const cycles = await searchQmetryTestCycles(qmetryConfigFromConnection(connection as QmetryConnectionInput), { startAt: 0, maxResults: 5 }); if (cycles.error) return res.json({ ok: false, error: cycles.error }); return res.json({ ok: true, count: cycles.total, sampleCycles: cycles.cycles }); } catch (err) { return res.status(500).json({ ok: false, error: (err as Error).message, requestId: requestId(req) }); } });
router.post('/input/sync', async (req: Request, res: Response) => { const filter = filterFromBody(req.body as Partial<FilterParams>); if (!filter.project) return res.status(400).json({ ok: false, error: 'Select a specific workspace before syncing imported data.', requestId: requestId(req) }); const dirs = projectDirs(filter.project); try { const sync = await refreshGeneratedOutputs(req, dirs, emptyConnections(), undefined, filter, 'import-only'); return res.json({ ok: true, ...sync, requestId: requestId(req) }); } catch (err) { logError(req, 'POST /input/sync:failed', err); return res.status(500).json({ ok: false, error: (err as Error).message, requestId: requestId(req) }); } });
router.post('/upload', (req: Request, res: Response) => { upload.single('file')(req, res, (err) => { if (err) return res.status(400).json({ error: err instanceof Error ? err.message : String(err), requestId: requestId(req) }); if (!req.file) return res.status(400).json({ error: 'No file uploaded', requestId: requestId(req) }); const project = requestProject(req); res.json({ ok: true, filename: req.file.filename, path: req.file.path, project, message: 'File staged for the selected workspace. Click Sync imported data to update dashboard data.' }); }); });
router.get('/input/files', (req: Request, res: Response) => { const project = requestProject(req); if (!project) return res.status(400).json({ error: 'Select a specific workspace before listing imported files.', requestId: requestId(req) }); const dirs = projectDirs(project); if (!fs.existsSync(dirs.inputDir)) return res.json([]); const files = fs.readdirSync(dirs.inputDir).filter((f) => !f.startsWith('.')).map((f) => { const stat = fs.statSync(path.join(dirs.inputDir, f)); return { name: f, size: stat.size, modifiedAt: stat.mtime.toISOString(), project }; }); res.json(files); });
router.delete('/input/:filename', async (req: Request, res: Response) => { const project = requestProject(req); if (!project) return res.status(400).json({ error: 'Select a specific workspace before deleting imported files.', requestId: requestId(req) }); const dirs = projectDirs(project); const filename = path.basename(req.params.filename); const filePath = path.join(dirs.inputDir, filename); if (!fs.existsSync(filePath)) return res.status(404).json({ error: 'File not found', requestId: requestId(req) }); fs.unlinkSync(filePath); try { const refresh = await refreshGeneratedOutputs(req, dirs, emptyConnections(), undefined, { project }, 'import-only'); return res.json({ ok: true, filename, project, ...refresh }); } catch (err) { const removed = clearOutputFiles(dirs); return res.json({ ok: true, filename, project, rebuilt: false, rowCounts: { executions: 0, issues: 0, uat: 0 }, removed, warnings: [`File removed, but imported data refresh failed: ${(err as Error).message}`] }); } });

export default router;
