name: Build

on:
  push:
    branches:
      - main
      - 'check/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Quiet Git messages
        run: |
          git config --global init.defaultBranch main
          git config --global advice.detachedHead false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Install dependencies
        run: npm ci --silent

      - name: Build workspaces
        run: bash .github/scripts/build-workspaces.sh
